version: '3'

services:
  app:
    build: .
    working_dir: /opt/app
    tty: true
    stdin_open: true
    volumes:
      - ./:/opt/app
      - /opt/app/node_modules/
      - /opt/app/.serverless/
    ports:
      - 3000:3000
    env_file:
      .env.deploy
