frameworkVersion: ^2.28.0
service: chankinlong-com
useDotenv: false

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: production
  memorySize: 256
  timeout: 3
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  logs:
    httpApi: true
    restApi: true

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
      - http: 'POST /contact'

plugins:
  - serverless-offline
  - serverless-api-gateway-throttling
  - serverless-domain-manager
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0
    noPrependStageInUrl: true

  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 10

  customDomain:
    domainName: 'chankinlong.com'
    basePath: ''
    stage: production
    createRoute53Record: false

  dotenv:
    include:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_USER
      - SMTP_PASS
      - SMTP_SENDER_EMAIL
      - CONTACT_RECEIVER_EMAILS
    required:
      env:
        - SMTP_HOST
        - SMTP_PORT
        - SMTP_SECURE
        - SMTP_USER
        - SMTP_PASS
        - SMTP_SENDER_EMAIL
        - CONTACT_RECEIVER_EMAILS
      file: true
